name: Build Python Script

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: List files (debug)
      run: ls -R

    - name: Run Python script
      run: python first.py

    - name: Package script as ZIP
      run: zip first_script.zip first.py

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: python-script-zip
        path: first_script.zip
